// An annotated screenshot for an SOP article.
//
// The image and the annotation geometry both come from `shots.json`, which is
// GENERATED by `npm run sop:shots` — the capture script drives the real app and
// records each hotspot's bounding box straight from the DOM. Nothing here is a
// hand-measured pixel coordinate, so a re-capture after a UI change moves the
// arrows with it instead of leaving them pointing at empty space.
//
// Annotations are drawn as a numbered marker + arrow on the image, with the
// wording in an HTML legend underneath rather than as SVG text. On a 390px
// warehouse phone, label text baked into a 1200px-wide image is unreadable; a
// legend stays full size and is selectable and translatable.
import React, { useState } from 'react';
import SHOTS from '../lib/sop/shots.json';

export const hasShot = (id) => Boolean(SHOTS[id]);

// Where the numbered marker sits relative to its hotspot, and which way the
// arrow points. The capture script picks a side per hotspot; this just resolves
// it to geometry in image pixel space.
function markerFor(h, imgW, imgH) {
  const OFF = Math.max(34, Math.round(imgW * 0.035)); // arrow length
  const mid = { x: h.x + h.w / 2, y: h.y + h.h / 2 };
  switch (h.side) {
    case 'left':   return { m: { x: Math.max(18, h.x - OFF), y: mid.y }, t: { x: h.x - 3, y: mid.y } };
    case 'right':  return { m: { x: Math.min(imgW - 18, h.x + h.w + OFF), y: mid.y }, t: { x: h.x + h.w + 3, y: mid.y } };
    case 'above':  return { m: { x: mid.x, y: Math.max(18, h.y - OFF) }, t: { x: mid.x, y: h.y - 3 } };
    default:       return { m: { x: mid.x, y: Math.min(imgH - 18, h.y + h.h + OFF) }, t: { x: mid.x, y: h.y + h.h + 3 } };
  }
}

export function SopShot({ id }) {
  const shot = SHOTS[id];
  const [failed, setFailed] = useState(false);
  // No capture yet (or the PNG was pruned) → render nothing rather than a broken
  // frame. Articles reference shots that may not have been captured on this box.
  if (!shot || failed) return null;
  const { file, w, h, caption, hotspots = [] } = shot;
  const r = Math.max(11, Math.round(w * 0.013)); // marker radius

  return (
    <figure className="ss-figure">
      <div className="ss-frame">
        <img className="ss-img" src={file} alt={caption || 'Screenshot'} width={w} height={h} loading="lazy" onError={() => setFailed(true)} />
        <svg className="ss-overlay" viewBox={`0 0 ${w} ${h}`} preserveAspectRatio="none" aria-hidden="true">
          <defs>
            <marker id={`ss-head-${id}`} viewBox="0 0 10 10" refX="9" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse">
              <path className="ss-head" d="M 0 0 L 10 5 L 0 10 z" />
            </marker>
          </defs>
          {hotspots.map((hs, i) => {
            const { m, t } = markerFor(hs, w, h);
            return (
              <g key={i}>
                <rect className="ss-hot" x={hs.x} y={hs.y} width={hs.w} height={hs.h} rx={6} />
                <line className="ss-arrow" x1={m.x} y1={m.y} x2={t.x} y2={t.y} markerEnd={`url(#ss-head-${id})`} />
                <circle className="ss-marker" cx={m.x} cy={m.y} r={r} />
                <text className="ss-marker-text" x={m.x} y={m.y + r * 0.36} textAnchor="middle" style={{ fontSize: r * 1.2 }}>{hs.n ?? i + 1}</text>
              </g>
            );
          })}
        </svg>
      </div>
      {hotspots.length > 0 && (
        <ol className="ss-legend">
          {hotspots.map((hs, i) => (
            <li key={i}><span className="ss-legend-n">{hs.n ?? i + 1}</span><span>{hs.label}</span></li>
          ))}
        </ol>
      )}
      {caption && <figcaption className="ss-cap">{caption}</figcaption>}
    </figure>
  );
}
