// A screen tutorial for an SOP article.
//
// The clip and its metadata come from `videos.json`, GENERATED by
// `scripts/upload-sop-videos.mjs` after `capture-sop-video.mjs` drives the real app
// in Playwright. Nothing here is hand-edited footage, so a UI change is re-recorded
// rather than re-cut — the same anti-rot property the annotated screenshots have.
//
// The clips are hosted on R2 (the bucket that already backs listing photos), not
// bundled: ~1 MB per minute across the library would otherwise sit in git history
// and in every Railway image.
//
// `preload="none"` is deliberate. These pages are read on warehouse phones, often on
// mobile data, and an article can carry several tutorials — preloading them would pull
// megabytes nobody asked for. Nothing is fetched until someone presses play.
//
// There is no voice track: the recorder has no TTS available, so narration is burnt-in
// captions. That is also the more useful form here — it survives a muted autoplay and a
// noisy warehouse, and it can be read by someone who does not have the volume.
import React, { useState } from 'react';
import VIDEOS from '../lib/sop/videos.json';

export const hasVideo = (id) => Boolean(VIDEOS[id] && VIDEOS[id].url);

const mmss = (s) => {
  const n = Number(s) || 0;
  return `${Math.floor(n / 60)}:${String(n % 60).padStart(2, '0')}`;
};

export function SopVideo({ id }) {
  const v = VIDEOS[id];
  const [failed, setFailed] = useState(false);
  // Not uploaded on this environment (or the object is gone) → render nothing rather
  // than a dead player, exactly as SopShot does for a missing capture.
  if (!v || !v.url || failed) return null;
  return (
    <figure className="sop-video">
      <video
        className="sop-video-el"
        src={v.url}
        controls
        preload="none"
        playsInline
        onError={() => setFailed(true)}
      />
      <figcaption className="sop-video-cap">
        <span className="sop-video-badge">Watch</span>
        {v.title}
        {v.seconds ? <span className="sop-video-len"> · {mmss(v.seconds)}</span> : null}
        <span className="sop-video-note">Captioned — no sound needed.</span>
      </figcaption>
    </figure>
  );
}
