// PH-team procedures: pricing, listing and store sync, plus the purchase-order
// desk they own. Superadmin sees this workspace too (Home → PH Team Workspace).
const PH = ['ph_team', 'admin', 'superadmin'];

export const PH_ARTICLES = [
  // --------------------------------------------------------- pricing/listing --
  {
    id: 'ph-new-inventory',
    title: 'Price & list new inventory',
    area: 'listing',
    roles: PH,
    summary: 'The core PH job: take what the warehouse just received, set a price per size, and mark it live on Intelligent Inventory, Alias, StockX and Shopify.',
    when: 'Every day, on whatever the warehouse scanned in.',
    diagram: 'listing-sync',
    shot: 'ph-grid',
    steps: [
      { do: 'Sign in → New Inventory.' },
      { do: 'Set the date range (Day / Week / Month) to the intake you are working.' },
      { do: 'Each row is one SKU and status: date, shoe, SKU, size chips, total quantity, and the II / AL / SX / SH badges.' },
      { do: 'Click a row to expand its per-size table. Every field is per size — cost, global indicator, final price, the four flags and a note can all differ between sizes.' },
      { do: 'Click Edit on the group to start changing it.' },
      { do: 'Check the Global indicator per size. It is fetched from Alias at intake, so it may already be filled — override it if it is wrong or missing.' },
      { do: 'Final price auto-calculates as GI plus the configured margin, rounded to whole dollars. Type over it if you want a different number.' },
      { do: 'Tap ↻ beside the Global indicator header to pull fresh Alias prices for just this group\'s sizes into the open draft.' },
      { do: 'Set II / AL / SX / SH per size as you actually create each listing, add a per-size note if useful, and Submit.' },
      { do: 'Click the shoe name or SKU to copy it to the clipboard — that is what you paste into the store listing forms.' },
    ],
    rules: [
      'Intelligent Inventory (II) is the master. The store flags describe reality — tick them when the listing exists, not before.',
      'A shoe marked "GOAT only" (purple chip) lists to Alias and II only. StockX and Shopify show N/A and are not editable, and they are excluded from the pending counts.',
      'No-box pairs never appear here. They are not postable until the warehouse resolves them.',
      'In-store buys never appear here either. They are listed by hand by the warehouse.',
    ],
    related: ['ph-grid-editing', 'ph-refresh-prices', 'ph-rescale', 'ph-price-inquiry', 'listings-sync-warehouse'],
    keywords: ['grid', 'per size', 'global indicator', 'final price', 'II', 'alias', 'stockx', 'shopify', 'copy sku', 'markup'],
  },
  {
    id: 'ph-grid-editing',
    title: 'Editing safely when other people are in the grid',
    area: 'listing',
    roles: PH,
    summary: 'How the grid stops two people overwriting each other, and what to do when it stops you.',
    when: 'Any time more than one person is working the same day\'s intake.',
    steps: [
      { do: 'Only one row can be open for editing per session. Other Edit buttons grey out until you submit or cancel.' },
      { do: 'If someone else holds a row you see a live "{name} editing…" badge with a pulsing dot. Work on a different row.' },
      { do: 'A held row releases on submit, on cancel, after 30 seconds of a dropped connection, or after an hour idle.' },
      { do: 'If your Submit comes back as a conflict, someone saved that row while you were typing. Let the grid reload the fresh values, then redo your change on top.' },
      { do: 'The list quietly refreshes every 15 seconds so new stock and other people\'s saves appear without a reload.', note: 'It pauses while you are editing or saving, so your draft is never yanked out from under you.' },
    ],
    rules: [
      'Two sessions of the same login are independent — signing in on a second device does not let you steal your own lock.',
      'The presence badge is advisory. The real protection is the conflict check on save, which is why a conflict is a normal outcome and not a failure.',
    ],
    related: ['ph-new-inventory', 'ph-history'],
    keywords: ['lock', 'presence', 'conflict', '409', 'concurrent', 'auto refresh', 'editing', 'shared account'],
  },
  {
    id: 'ph-refresh-prices',
    title: 'Refresh prices from Alias',
    area: 'listing',
    roles: PH,
    summary: 'Pull the current Global Indicator for everything on screen and recompute Final price.',
    when: 'Prices have moved, or the margin was changed and unlisted stock needs re-pricing.',
    steps: [
      { do: 'Set the date filter so the grid shows exactly what you want re-priced.' },
      { do: 'Tap "↻ Refresh prices" in the toolbar.' },
      { do: 'Read the notice afterwards — it reports how many sizes fell back to the "With You" basis.' },
      { do: 'For one group only, use the ↻ beside the Global indicator header inside that group\'s size table instead.' },
    ],
    rules: [
      'Manual price overrides are kept only for pairs that are already listed (on II or any store). A live listing is not disturbed.',
      'Unlisted pairs always take the fresh Final = GI × current margin, so a margin change actually lands.',
      'Sold and shipped pairs are excluded, and the refresh is blocked while a row is being edited.',
      'An amber "WY" chip beside a GI means the consigned price was empty and the "With You" price was used instead. Typing a GI by hand clears that chip.',
    ],
    related: ['ph-new-inventory', 'admin-settings', 'ph-price-inquiry'],
    keywords: ['GI', 'global indicator', 'consigned', 'with you', 'WY', 'margin', 'override', 'bulk refresh'],
  },
  {
    id: 'ph-rescale',
    title: 'Work the Rescale Stock worklist',
    area: 'rescale',
    roles: PH,
    summary: 'Re-list pairs the warehouse re-scanned — returns, re-listings, recounts and transfers.',
    when: 'The Restock badge is above zero.',
    diagram: 'rescale-loop',
    steps: [
      { do: 'PH home → Rescale Stock.' },
      { do: 'The grid works exactly like New Inventory, but it lists pairs the warehouse flagged for restock, dated by when they were re-scanned.' },
      { do: 'Price and set the store flags per size the same way.' },
      { do: 'Tap "✓ Restocked" when the pair is properly re-listed. It drops off the worklist and behaves as normal stock again.' },
    ],
    rules: [
      'No-box pairs are excluded here too.',
      'In-store pairs can never appear on this worklist — the app refuses to rescale them at source.',
    ],
    related: ['rescale-stock', 'ph-new-inventory', 'ph-request-rescale'],
    keywords: ['restock', 'worklist', 'returned', 'relisting', 'restocked', 're-list'],
  },
  {
    id: 'ph-request-rescale',
    title: 'Request a rescale (ask the warehouse to recount)',
    area: 'rescale',
    roles: PH,
    summary: 'Flag a SKU whose numbers look wrong, get the warehouse to physically count it, then list against the real figures.',
    when: 'The system quantity does not match what you believe we hold.',
    diagram: 'rescale-loop',
    steps: [
      { do: 'PH home → Request Rescale → "+ New request".' },
      { do: 'Enter the SKU and tap Search to auto-fill the shoe name.' },
      { do: 'Enter the sizes and quantities you believe are correct — this is the "reported" side.' },
      { do: 'Add the current price, pick a reason (mismatch, quantity, recount, returned, re-listing, other), and write a note explaining what you are seeing.' },
      { do: 'Submit. The request is "open" and appears on the warehouse\'s Rescale Requests screen.' },
      { do: 'When it comes back "audited", read the comparison grid — reported on top, actual underneath, red for mismatch and green for match.' },
      { do: 'The per-size listing table then shows inline. Tap ↻ beside Global indicator to fill GI per size, check the Final prices, set II / AL / SX / SH, and Save listing.' },
    ],
    rules: [
      'A request is a counting exercise about a SKU, not about specific pairs. Saving the listing here records what you listed against the request — it does not flip the inventory sync flags.',
      'To actually change inventory records, the warehouse rescales the pairs so they land on the Rescale Stock worklist.',
    ],
    related: ['rescale-requests-audit', 'ph-rescale'],
    keywords: ['request', 'audit', 'reported', 'actual', 'mismatch', 'recount', 'listing table', 'save listing'],
  },
  {
    id: 'ph-price-inquiry',
    title: 'Price inquiry — what is this worth right now?',
    area: 'listing',
    roles: PH,
    summary: 'A read-only live Alias lookup for any SKU. Nothing is saved and no inventory is touched.',
    when: 'Deciding whether to buy, or sanity-checking a price before you list.',
    steps: [
      { do: 'PH home → Price Inquiry.' },
      { do: 'Paste a SKU and search. The canonical title and the full size run come back.' },
      { do: 'Tap a size chip to fetch that size on the spot. Tap it again to remove it.' },
      { do: 'Or tap "Price all" to fetch the whole size run in one request.' },
      { do: 'Read the table per size: Lowest ask, Highest offer, Last sold, Global indicator, and Final (GI + margin).' },
    ],
    rules: [
      'A "—" means Alias reported nothing for that size — no current listing, offer or sale. It is not an error.',
      'This screen writes nothing. Use New Inventory or Rescale Stock to actually set a price.',
    ],
    related: ['ph-new-inventory', 'ph-refresh-prices'],
    keywords: ['lookup', 'lowest ask', 'highest offer', 'last sold', 'alias', 'read only', 'quote'],
  },
  {
    id: 'ph-image-finder',
    title: 'Find and build listing images',
    area: 'listing',
    roles: PH,
    summary: 'Source photos for a SKU from Nike, adidas and the marketplaces, then compose them onto the branded template — cut out, positioned, with a spec slide.',
    when: 'A SKU needs listing imagery, or the warehouse originals are not good enough to post.',
    steps: [
      { do: 'PH home → Find Image Listings. Enter or scan a SKU.' },
      { do: 'Every image source is queried at once and shown as its own strip — Nike/Jordan and adidas label their angles, the marketplaces are numbered.' },
      { do: 'Five slots are pre-filled with the best candidate per angle: side, diagonal, top, outsole, rear. Tap a slot to make it active, then tap any gallery image to assign it.' },
      { do: 'Use "Upload" on a slot to supply your own photo for an angle nothing covers.' },
      { do: 'Check the title field — it is pre-filled from the API and gets stamped on every branded slide.' },
      { do: 'Tap "Brand & Fill" to render a preview. Nothing is saved yet.' },
      { do: 'Fix anything that looks wrong: "Adjust size" to drag, pinch or scale the shoe on the template; "Cutout" to re-cut a shoe that came out badly.' },
      { do: 'Choose the output size — 1600 (design size) or 1400 (eBay\'s recommendation).' },
      { do: 'Tap "Upload to server" to commit. Then "Download all" for the zip you upload to the marketplaces.' },
    ],
    rules: [
      'The flow is find → angles → Brand & Fill → review → Upload. Brand & Fill is a preview; Upload is the commit.',
      'Files come out named <sku>-<position>-<angle>, in marketplace upload order: 1 lateral, 2 diagonal, 3 top, 4 outsole, 5 heel, 6 spec, 7 welcome.',
      'A "throttled" error on a slot means the cutout service is out of credit. Re-cut once it is topped up rather than saving a bad slide.',
      'iPhone HEIC photos are converted in the browser at upload time. If a raw HEIC is rejected, re-save it as JPEG.',
    ],
    related: ['ph-edited-photos', 'listing-photos-intake'],
    keywords: ['image finder', 'brand and fill', 'template', 'cutout', 'nike', 'adidas', 'goat', 'stockx', 'spec slide', 'download all', 'zip'],
  },
  {
    id: 'ph-edited-photos',
    title: 'Upload finished listing images',
    area: 'listing',
    roles: PH,
    summary: 'Put your own edited images against a SKU. They take precedence over the warehouse originals without ever replacing them.',
    when: 'You edited the photos elsewhere and just need them on the record.',
    steps: [
      { do: 'PH home → Find Image Listings → enter the SKU. The manage view lists the SKU\'s photos.' },
      { do: 'Drop up to 7 images on the drop-zone, or tap to select them.' },
      { do: 'The angles are fixed — drag the photos (or use ◀/▶) until each sits on the right angle. Slots 6 and 7 are extras that never become the thumbnail.' },
      { do: 'Upload. Each image is compressed and stored, and becomes the SKU\'s preferred image for that angle.' },
      { do: 'Use "Download all" to grab everything for the SKU — your edits plus the warehouse originals — as a zip.' },
    ],
    rules: [
      'A PH upload never overwrites a warehouse original. Both are kept; yours wins per angle where it exists.',
      'If the SKU already has edited images the drop-zone hides behind a "Replace listing images" button. Replacing only rewrites the edited set.',
      'The thumbnail prefers the side angle first, then your edit over the warehouse shot — so editing a non-side angle will not hijack a good side photo.',
    ],
    related: ['ph-image-finder', 'listing-photos-intake'],
    keywords: ['upload', 'bulk', 'reorder', 'drag', 'extra1', 'extra2', 'replace', 'originals', 'precedence', 'zip'],
  },
  {
    id: 'ph-history',
    title: 'Read the history and attribution',
    area: 'listing',
    roles: PH,
    summary: 'Who set this price, and was it a person or the system?',
    when: 'A number looks wrong and you need to know where it came from.',
    steps: [
      { do: 'In the grid, expand a group and tap History on a size.' },
      { do: 'Read the timeline: who did what and when, in EST. Identical repeated edits are collapsed.' },
      { do: 'The "Added by" column is the first PH person to touch the group. "Last edited by" appears once anyone has edited it since.' },
    ],
    rules: [
      '"(system-generated)" on a Global indicator means the automatic Alias fetch set it. Without it, a person typed it.',
      'A Final price is system-generated while it still equals GI × margin. It only shows a name once someone overrode that calculation.',
      'History is readable by warehouse, PH and admin alike.',
    ],
    related: ['ph-grid-editing', 'ph-refresh-prices', 'inventory-browse'],
    keywords: ['audit', 'timeline', 'added by', 'last edited by', 'system generated', 'events', 'who changed'],
  },
  {
    id: 'ph-nobox-view',
    title: 'No Box (PH view)',
    area: 'listing',
    roles: PH,
    summary: 'See what is stuck without a box and therefore missing from your listing grid.',
    when: 'Stock you expected to price is not showing up.',
    steps: [
      { do: 'PH home → No Box / Not Ready.' },
      { do: 'Read the list. These pairs are not postable and are deliberately hidden from New Inventory.' },
      { do: 'Chase the warehouse — they resolve them by finding the box.' },
    ],
    rules: [
      'This page is view-only for PH. Only warehouse and admin can resolve a no-box pair.',
    ],
    related: ['nobox-resolve', 'ph-new-inventory'],
    keywords: ['no box', 'missing stock', 'not postable', 'view only', 'hidden'],
  },

  // ------------------------------------------------------------ purchase POs --
  {
    id: 'po-create',
    title: 'Open a purchase order for a supplier',
    area: 'po',
    roles: PH,
    summary: 'Create the order shell and its shipping labels before anything has been packed, so the supplier can scan out against it.',
    when: 'You have bought from a supplier who will ship to us.',
    diagram: 'po-flow',
    shot: 'po-create',
    steps: [
      { do: 'PH home → New Batch (Purchase Order).' },
      { do: 'Pick the supplier account, set the tag code and date of purchase.' },
      { do: 'Add one row per shipping label, each with its real courier tracking number and its courier.' },
      { do: 'Or tap "Upload labels PDF" — one shipping label per page — and each page\'s tracking number and courier are read off it automatically.', note: 'Blanks are left where a page could not be read. Fill those in by hand.' },
      { do: 'Check every courier dropdown before saving. The courier is what makes tracking pull from the right carrier.' },
      { do: 'Create the order. It gets a PO code (PO-100037) and starts as "draft". Tracking registration happens immediately, so pushes work even if the supplier never opens the portal.' },
    ],
    rules: [
      'Registering a tracking number consumes one tracking-service credit at creation time.',
      'A multi-label order stays "draft" until every label has been shipped by the supplier.',
      'Boxes routinely arrive before the order says "shipped" — that is fine, the warehouse can receive against a draft.',
    ],
    related: ['po-overview', 'po-onbehalf', 'receive-against-po', 'supplier-scanout'],
    keywords: ['new batch', 'PO code', 'labels', 'tracking', 'carrier', 'courier', 'pdf import', 'draft'],
  },
  {
    id: 'po-overview',
    title: 'Track purchase orders and shipments',
    area: 'po',
    roles: PH,
    summary: 'Every order you opened, its status, and live tracking per shipping label.',
    when: 'Chasing a shipment, or checking whether a supplier has actually packed.',
    shot: 'po-overview',
    steps: [
      { do: 'PH home → Purchase Orders.' },
      { do: 'Each order shows a status chip, how many of its labels are shipped, how many are delivered, and the unit count.' },
      { do: 'Tap an order to expand per-label tracking: status, carrier and the latest checkpoint.' },
      { do: 'Use "Refresh all" for the whole order, or the per-label refresh to spend fewer tracking credits.' },
      { do: 'Print the manifest with "Manifest PDF" → "Per box" (a page per label) or "Whole order" (one list).', note: 'The warehouse can print the same thing from the receiving banner and from PO Reconciliation — you do not need to send it to them.' },
      { do: 'Read the sub-status chip when something is off — "Being returned to sender", "Held — customs", "Delayed". Red means act, amber means watch.' },
    ],
    rules: [
      '"With supplier · label made" means the label exists but the courier has not taken it yet. That is the supplier\'s move, not ours.',
      'Tracking status only ever moves forwards. A late lower update will not drag a delivered box backwards.',
      'Replacement shipments are titled "Replacement shipment" and are excluded from the supplier\'s "N of N labels shipped" count — that number describes their packing job.',
    ],
    related: ['po-create', 'po-resolution', 'reconcile-warehouse'],
    keywords: ['tracking', '17track', 'checkpoint', 'delivered', 'in transit', 'sub status', 'refresh', 'carrier', 'exception', 'print manifest', 'packing slip', 'pdf'],
  },
  {
    id: 'po-onbehalf',
    title: 'Enter a supplier\'s manifest for them',
    area: 'po',
    roles: PH,
    summary: 'Three ways to record what a supplier says they shipped when they will not use the portal.',
    when: 'The supplier sent a list by message, or gave nothing at all.',
    steps: [
      { do: 'Per label — PH home → Purchase Orders → open a draft order → "Add items on their behalf" on a pending label. Scan or type each SKU, size and quantity.' },
      { do: 'Whole order — if the supplier gave ONE list for the whole purchase rather than per box, use "Add whole-order manifest" instead. Reconciliation then counts the order as a whole.' },
      { do: 'Nothing at all — do not enter anything. The warehouse receives blind, and the report says "No manifest provided — received blind" instead of inventing a wall of overages.' },
    ],
    rules: [
      'An order is either per-label or whole-order, never both. The app refuses the second style once the first is in use.',
      'On-behalf lines are stamped with your name for us, but the supplier only ever sees "{business}\'s Staff". They cannot see which of us typed it.',
      'If the supplier later edits a line you entered, they take ownership of it.',
      'You can only fill a label while the order is draft and that label is still pending — the same window the supplier has.',
    ],
    related: ['po-create', 'reconcile-warehouse', 'supplier-scanout'],
    keywords: ['manifest', 'on behalf', 'non-compliant', 'blind', 'whole order', 'scan order', 'attribution'],
  },
  {
    id: 'po-resolution',
    title: 'Resolve a short or wrong purchase order',
    area: 'po',
    roles: PH,
    summary: 'What happens after an order comes up short: contact the supplier, agree an outcome, record the reference, confirm it settled.',
    when: 'Reconciliation shows discrepancies and money or stock is owed.',
    diagram: 'po-resolution',
    steps: [
      { do: 'Open the order in PO Reconciliation and work the four-step checklist: contacted → outcome → reference → settled.' },
      { do: 'Tick "contacted" once you have actually raised it with the supplier.' },
      { do: 'Pick the outcome: a refund/credit, a replacement shipment, or a write-off.' },
      { do: 'For a refund, record the agreed amount, then later the amount that actually arrived. A short payment is flagged rather than closing green.' },
      { do: 'For a replacement, log it as a new label on this same order with its tracking number. The order reopens for receiving and the thread says so.' },
      { do: 'Ask the supplier to list what they are actually reshipping, on the replacement label in their portal. If they will not, enter it for them from PO Overview → the order → "Add items on their behalf" on the replacement shipment.', note: 'That list is what the warehouse ticks off when the box lands, instead of scanning a reship blind.' },
      { do: 'Use the internal thread to record what was said. Every checklist action posts into it, so the thread is the audit trail.' },
      { do: 'Write the supplier-facing note in "Note to the supplier". That is the ONLY thing the supplier can read.' },
    ],
    rules: [
      'The thread is internal. If you only type there, the supplier has been told nothing — that is why the amber nudge appears.',
      'Use "Send to supplier" on any internal comment to promote it into the supplier-facing note.',
      'Every step can be undone. A refund that never lands has to be re-openable.',
      'A replacement label CAN carry a manifest, and its units are deliberately left out of the expected count. Those pairs were already declared on the original order and already counted short, so counting them twice would leave the order reading short forever. The reship list is a checklist for the warehouse, never a second claim.',
      'The replacement manifest stays editable until the order is archived — unlike the supplier\'s own labels, which lock once the order leaves draft.',
      'When the reship is scanned in, the order goes clean, auto-reconciles, and "Replacement received" ticks itself.',
    ],
    related: ['reconcile-warehouse', 'po-overview', 'supplier-portal-read'],
    keywords: ['refund', 'credit', 'replacement', 'reship', 'writeoff', 'settled', 'thread', 'comment', 'note to supplier', 'nudge'],
  },
];
